# Version simplifiée pour débugger l'erreur de service account
steps:
  # Construction Docker seulement
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'src/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/digital-social-score:${_TAG}'
      - '.'

  # Push vers Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/digital-social-score:${_TAG}'

images:
  - 'gcr.io/$PROJECT_ID/digital-social-score:${_TAG}'

substitutions:
  _TAG: 'manual-build'

options:
  # SOLUTION: Utiliser CLOUD_LOGGING_ONLY sans service account
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'